import { ApiEinsatzResponse, Einsatz } from '../@types'

export const testData: Einsatz[] = [
  {
    id: '2022-200',
    number: '200',
    date: '2022-11-01',
    keyword: 'THL-1',
    description: 'Unfall mit 2 Fahrzeugen, eine Person noch im Fahrzeug',
    vehicles: ['10/1', '40/2', '21/1 + VSA'],
    imageUrls: ['https://alt.feuerwehr-koenigsbrunn.org/images/einsatz/2022027/P1090542_web.jpg'],
  },
  {
    id: '2022-201',
    number: '201',
    date: '2022-11-02',
    keyword: 'KTL',
    description: 'KTL-Einsatz',
    vehicles: ['30/1', '40/2'],
  },
  {
    id: '2022-202',
    number: '202',
    date: '2022-11-05',
    keyword: 'Tragehilfe Rettungsdienst',
    description: 'Unterstützung Rettungsdienst',
    vehicles: ['10/1', '40/2'],
  },
]

export const data_2020: ApiEinsatzResponse[] = [
  {
    ID: '2020383',
    nr: '301',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '25.12.20',
    adr: 'Raber Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020382',
    nr: '300',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße überschw',
    datum: '24.12.20',
    adr: 'Gartenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020381',
    nr: '299',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA-P',
    datum: '20.12.20',
    adr: 'Chiemseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020380',
    nr: '298',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Whg öffnen akut',
    datum: '18.12.20',
    adr: 'R.-Wagner-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020379',
    nr: '297',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Rettung Kl Tier',
    datum: '15.12.20',
    adr: 'Alpenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020378',
    nr: '296',
    typ: 'T',
    stw: 'Sonstige',
    fzg: '10/1, 40/2',
    title: 'VU nur RD',
    datum: '11.12.20',
    adr: 'Bobinger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020376',
    nr: '295',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Schmorbrand',
    datum: '10.12.20',
    adr: 'Donauwörther Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020375',
    nr: '294',
    typ: 'T',
    stw: 'THL 1',
    fzg: '40/2, 55/1',
    title: 'Auslaufender Kraftstoff ',
    datum: '08.12.20',
    adr: 'Germanenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020377',
    nr: '293',
    typ: 'T',
    stw: 'Tragehilfe Rettungsdienst',
    fzg: '40/2',
    title: 'Tragehilfe',
    datum: '01.12.20',
    adr: 'Adalbert-Stifter-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020374',
    nr: '292',
    typ: 'T',
    stw: 'Tragehilfe Rettungsdienst',
    fzg: '40/2',
    title: 'Tragehilfe',
    datum: '30.11.20',
    adr: 'Adalbert-Stifter-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020373',
    nr: '291',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '30.11.20',
    adr: 'Bgm.-Wohlfarth-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020365',
    nr: '290',
    typ: 'T',
    stw: 'THL ABC',
    fzg: '10/1, 40/1, 40/2',
    title: 'Gas-Geruch',
    datum: '29.11.20',
    adr: 'Schlesierstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020364',
    nr: '289',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/1',
    title: 'Auffahrunfall',
    datum: '26.11.20',
    adr: 'B17 Augsburg » Landsberg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020363',
    nr: '288',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 21/1 + VSA',
    title: 'Auffahrunfall mit mehreren PKW',
    datum: '26.11.20',
    adr: 'B17 Augsburg » Landsberg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020372',
    nr: '287',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'verletztes Tier',
    datum: '26.11.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020362',
    nr: '286',
    typ: 'S',
    stw: 'HvO (Helfer vor Ort)',
    fzg: '10/1',
    title: 'Medizinische Hilfeleistung',
    datum: '25.11.20',
    adr: 'St.-Johannes-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020361',
    nr: '285',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '20.11.20',
    adr: 'Frühlingstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020371',
    nr: '284',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'verletztes Tier',
    datum: '19.11.20',
    adr: 'Rathausstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020366',
    nr: '283',
    typ: 'S',
    stw: 'Kleintierrettung',
    fzg: '65/1',
    title: 'Tierhilfe',
    datum: '19.11.20',
    adr: 'Dietrich-Bonhoeffer-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020360',
    nr: '282',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 40/2',
    title: 'Angebrannte Speisen ',
    datum: '18.11.20',
    adr: 'Holbeinstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020359',
    nr: '281',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Wohnung öffnen',
    datum: '15.11.20',
    adr: 'A.-Stifter-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020370',
    nr: '280',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Fundtier',
    datum: '13.11.20',
    adr: 'Lerchenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020358',
    nr: '279',
    typ: 'F',
    stw: 'Brand 2',
    fzg: '10/1, 40/1 ',
    title: 'Rauchwarnmelder',
    datum: '12.11.20',
    adr: 'Enzianstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020369',
    nr: '278',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'kein Eingreifen',
    datum: '11.11.20',
    adr: 'Alter Postweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020368',
    nr: '277',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierhilfe',
    datum: '03.11.20',
    adr: 'Nibelungenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020357',
    nr: '276',
    typ: 'T',
    stw: 'Sonstige',
    fzg: '10/1, 40/2',
    title: 'KTL-Einsatz',
    datum: '01.11.20',
    adr: 'A.-Stifter-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020367',
    nr: '275',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, /30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '31.10.20',
    adr: 'Eichenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020333',
    nr: '274',
    typ: 'T',
    stw: 'Wasserrettung',
    fzg: '10/1, 40/2, 14/1 + Boot, 30/1, 40/1, 41/1; BF Augsburg mit Taucher',
    title: 'Person in Wasser',
    datum: '31.10.20',
    adr: 'Alter Postweg',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020332',
    nr: '273',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1',
    title: 'BMA: Fehlalarm',
    datum: '30.10.20',
    adr: 'Föllstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020331',
    nr: '272',
    typ: 'T',
    stw: 'Tragehilfe Rettungsdienst',
    fzg: '10/1, 40/2',
    title: 'Unterstützung des Rettungsdienstes',
    datum: '26.10.20',
    adr: 'R.-Wagner-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020330',
    nr: '271',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Rauchentwicklung im Gebäude',
    datum: '24.10.20',
    adr: 'Blumenallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020329',
    nr: '270',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '24.10.20',
    adr: 'Blumenallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020356',
    nr: '269',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierrettung',
    datum: '23.10.20',
    adr: 'Blumenallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020355',
    nr: '268',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '20.10.20',
    adr: 'Ulrichsplatz',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020328',
    nr: '267',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '20.10.20',
    adr: 'Geschw.-Scholl-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020327',
    nr: '266',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 40/2; FF Bobingen 40/1, 30/1',
    title: 'Kellerbrand',
    datum: '19.10.20',
    adr: 'Martin-Luther-Straße',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020354',
    nr: '265',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierrettung',
    datum: '17.10.20',
    adr: 'Simpertstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020326',
    nr: '264',
    typ: 'F',
    stw: 'HvO',
    fzg: '10/1',
    title: 'HvO',
    datum: '16.10.20',
    adr: 'Lerchenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020325',
    nr: '263',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '10/1, 40/1, 40/2',
    title: 'Kleinbrand',
    datum: '14.10.20',
    adr: 'Bgm.-Wohlfarth-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020324',
    nr: '262',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '14.10.20',
    adr: 'Wertachstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020323',
    nr: '261',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1',
    title: 'BMA: Fehlalarm',
    datum: '14.10.20',
    adr: 'Blumenallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020322',
    nr: '260',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Wasser i Gebäud',
    datum: '14.10.20',
    adr: 'Augsburger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020321',
    nr: '259',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '10.10.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020320',
    nr: '258',
    typ: 'B',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1',
    title: 'BMA: Fehlalarm',
    datum: '08.10.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020319',
    nr: '257',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '06.10.20',
    adr: 'Lechstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020318',
    nr: '256',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '10/1, 30/1, 40/2',
    title: 'KTL-Einsatz',
    datum: '04.10.20',
    adr: 'Eichenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020317',
    nr: '255',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '04.10.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020316',
    nr: '254',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '03.10.20',
    adr: 'Brunnenbachstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020353',
    nr: '253',
    typ: 'F',
    stw: 'Öl/Benzin',
    fzg: '65/1',
    title: 'Ölspur, kein Eingreifen',
    datum: '02.10.20',
    adr: 'Schwabenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020314',
    nr: '252',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '02.10.20',
    adr: 'Rotdornstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020313',
    nr: '251',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1',
    title: 'BMA: Fehlalarm',
    datum: '28.09.20',
    adr: 'Karwendelstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020312',
    nr: '250',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2, 55/1; Florian Bobingen 30/1',
    title: 'Kellerbrand',
    datum: '28.09.20',
    adr: 'Weizenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020352',
    nr: '249',
    typ: 'S',
    stw: 'Unterstützung Polizei',
    fzg: '65/1',
    title: 'Unterstützung Polizei',
    datum: '27.09.20',
    adr: 'Buchenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020311',
    nr: '248',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '26.09.20',
    adr: 'Eichenplatz',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020351',
    nr: '247',
    typ: 'S',
    stw: 'HvO (Helfer vor Ort)',
    fzg: '10/1',
    title: 'Notarztzubringer',
    datum: '26.09.20',
    adr: 'Schwabenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020350',
    nr: '246',
    typ: 'S',
    stw: 'HvO (Helfer vor Ort)',
    fzg: '10/1',
    title: 'Notarztzubringer',
    datum: '25.09.20',
    adr: 'Schwalbenweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020310',
    nr: '245',
    typ: 'T',
    stw: 'Tragehilfe',
    fzg: '40/2',
    title: 'Tragehilfe Rettungsdienst',
    datum: '25.09.20',
    adr: 'A.-Dürer-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020309',
    nr: '244',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '22.09.20',
    adr: 'Schwabenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020349',
    nr: '243',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Kein Eingreifen notwendig',
    datum: '22.09.20',
    adr: 'Bachstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020308',
    nr: '242',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Wohnung öffnen',
    datum: '22.09.20',
    adr: 'Pettenkoferstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020307',
    nr: '241',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '21.09.20',
    adr: 'Hunnenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020306',
    nr: '240',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Rauchentwicklung ',
    datum: '21.09.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020305',
    nr: '239',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Schmorbrand',
    datum: '21.09.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020304',
    nr: '238',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Whg öffnen akut',
    datum: '18.09.20',
    adr: 'Tegernseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020303',
    nr: '237',
    typ: 'B',
    stw: 'Brand 2',
    fzg: '10/1, 40/1, 41/1',
    title: 'Rauchwarnmelder',
    datum: '16.09.20',
    adr: 'Narzissenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020302',
    nr: '236',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'allgemein',
    datum: '15.09.20',
    adr: 'Benzstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020300',
    nr: '235',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Rauchentw',
    datum: '12.09.20',
    adr: 'Messerschmittring',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020299',
    nr: '234',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Whg öffnen akut',
    datum: '12.09.20',
    adr: 'Rosenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020298',
    nr: '233',
    typ: 'F',
    stw: 'Sonstige',
    fzg: '65/1',
    title: 'Ölspur, kein Eingreifen',
    datum: '11.09.20',
    adr: 'Lechstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020348',
    nr: '232',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Kein Eingreifen notwendig',
    datum: '09.09.20',
    adr: 'Messerschmittring',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020297',
    nr: '231',
    typ: 'F',
    stw: 'Erkundung',
    fzg: '',
    title: 'Erkundung',
    datum: '08.09.20',
    adr: 'St.-Johannes-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020296',
    nr: '230',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '03.09.20',
    adr: 'St.-Ulrich-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020294',
    nr: '229',
    typ: 'T',
    stw: 'THL Wasser',
    fzg: '10/1, 14/1 + Boot, 40/2, 30/1',
    title: 'P Wassernot',
    datum: '03.09.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020293',
    nr: '228',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '01.09.20',
    adr: 'Föllstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020292',
    nr: '227',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '31.08.20',
    adr: 'Messerschmittring',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020291',
    nr: '226',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße überschwemmt',
    datum: '30.08.20',
    adr: 'Gartenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020347',
    nr: '225',
    typ: 'T',
    stw: 'Unwetternotdienst',
    fzg: '65/1, 30/1',
    title: 'Sturmschaden',
    datum: '26.08.20',
    adr: 'Nördlinger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020290',
    nr: '224',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Brandgeruch',
    datum: '25.08.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020289',
    nr: '223',
    typ: 'T',
    stw: 'Unwetter',
    fzg: '10/1, 40/2, 40/1',
    title: 'Baum/Ast Fahrb',
    datum: '25.08.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020346',
    nr: '222',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Kein Eingreifen notwendig',
    datum: '24.08.20',
    adr: 'Enzianstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020288',
    nr: '221',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2',
    title: 'PKW gegen Garagentor',
    datum: '24.08.20',
    adr: 'Tegernseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020287',
    nr: '220',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '21.08.20',
    adr: 'Weizenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020286',
    nr: '219',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '20.08.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020345',
    nr: '218',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Kein Eingreifen notwendig',
    datum: '20.08.20',
    adr: 'Karwendelstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020284',
    nr: '217',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '20.08.20',
    adr: 'Augsburger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020344',
    nr: '216',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Vogel einfangen',
    datum: '19.08.20',
    adr: 'Germanenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020343',
    nr: '215',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Kein Eingreifen notwendig',
    datum: '19.08.20',
    adr: 'Ludwig-Martini-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020283',
    nr: '214',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '16.08.20',
    adr: 'Sperberstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020282',
    nr: '213',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '14.08.20',
    adr: 'Pettenkoferstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020281',
    nr: '212',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '14.08.20',
    adr: 'Königsallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020285',
    nr: '211',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Ölspur',
    datum: '20.08.20',
    adr: 'Heinkelstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020280',
    nr: '210',
    typ: 'B',
    stw: 'B Gefahrstoff',
    fzg: '10/1, 40/1, 40/2, 30/1, 21/1, 48/1, 55/1',
    title: 'B Tankwagen',
    datum: '09.08.20',
    adr: 'Messerschmittring',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020277',
    nr: '209',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Brand Dach',
    datum: '09.08.20',
    adr: 'Geschw.-Scholl-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020276',
    nr: '208',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 65/1',
    title: 'VU mit Motorrad',
    datum: '08.08.20',
    adr: 'Bobinger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020275',
    nr: '207',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Wasser i Keller',
    datum: '08.08.20',
    adr: 'Silcherstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020274',
    nr: '206',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '07.08.20',
    adr: 'Föllstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020273',
    nr: '205',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '05.08.20',
    adr: 'Föllstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020272',
    nr: '204',
    typ: 'B',
    stw: 'Brand 4',
    fzg: '10/1, 40/1, 30/1, 40/2, 21/1, 48/1; FF Oberottmarshausen 21/1, BF Augsburg: AB Wasser',
    title: 'Brand Silo',
    datum: '04.08.20',
    adr: 'Grenzweg',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020271',
    nr: '203',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1',
    title: 'BMA: Angebrannte Speisen',
    datum: '04.08.20',
    adr: 'Asternstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020270',
    nr: '202',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 21/1 + VSA',
    title: 'VU mit 2 PKW',
    datum: '03.08.20',
    adr: 'B17 Augsburg » Landsberg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020269',
    nr: '201',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Täuschungsalarm',
    datum: '02.08.20',
    adr: 'Königsallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020268',
    nr: '200',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '02.08.20',
    adr: 'Schulstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020267',
    nr: '199',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2, 65/1',
    title: 'BMA: Fehlalarm',
    datum: '02.08.20',
    adr: 'Schulstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020266',
    nr: '198',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1, 21/1 + VSA,',
    title: 'Brand Mittelstreifen',
    datum: '01.08.20',
    adr: 'B17 Landsberg > Augs 740  3.0',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020342',
    nr: '197',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Kein Eingreifen notewendig',
    datum: '01.08.20',
    adr: 'Ahornstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020265',
    nr: '196',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 21/1 + VSA, 40/2,',
    title: 'Brand Mittelstreifen',
    datum: '31.07.20',
    adr: 'B17 Landsberg > Augs 720  2.0',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020264',
    nr: '195',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '10/1, 40/1, 21/1 + VSA, 41/1',
    title: 'Fehlalarm',
    datum: '31.07.20',
    adr: 'B17 Landsberg > Augs 700 4.0',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020263',
    nr: '194',
    typ: 'B',
    stw: 'Brand 4',
    fzg: '10/1, 40/1, 30/1, 40/2, 21/1',
    title: 'Brand Altenwohnheim',
    datum: '29.07.20',
    adr: 'Blumenallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020262',
    nr: '193',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Irrtum des Meldenden',
    datum: '28.07.20',
    adr: 'Buchenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020341',
    nr: '192',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: '',
    datum: '27.07.20',
    adr: 'Alter Postweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020261',
    nr: '191',
    typ: 'S',
    stw: 'Sonstige',
    fzg: '10/1',
    title: 'Notarzt-Zubringer',
    datum: '26.07.20',
    adr: 'Edelweißring',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020260',
    nr: '190',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '10/1, 30/1, 40/2',
    title: 'KTL-Einsatz',
    datum: '26.07.20',
    adr: 'Donauwörther Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020259',
    nr: '189',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '10/1, 40/2, 30/1',
    title: 'KTL-Einsatz',
    datum: '25.07.20',
    adr: 'Chiemseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020340',
    nr: '188',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierrettung',
    datum: '24.07.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020258',
    nr: '187',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '24.07.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020257',
    nr: '186',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Auslaufender Kraftstoff',
    datum: '19.07.20',
    adr: 'Germanenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020256',
    nr: '185',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Keller unter Wasser',
    datum: '19.07.20',
    adr: 'Liebenauer Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020255',
    nr: '184',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Brand Unrat',
    datum: '17.07.20',
    adr: 'Wandalenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020339',
    nr: '183',
    typ: 'S',
    stw: 'Unterstützung Polizei',
    fzg: '65/1',
    title: 'Unterstützung Polizei',
    datum: '17.07.20',
    adr: 'Gerstenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020254',
    nr: '182',
    typ: 'S',
    stw: 'Tragehilfe',
    fzg: '10/1, 40/2',
    title: 'Unterstützung des Rettungsdienstes',
    datum: '17.07.20',
    adr: 'Dornierstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020338',
    nr: '181',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierrettung',
    datum: '13.07.20',
    adr: 'Aumühlstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020251',
    nr: '180',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Ölspur',
    datum: '13.07.20',
    adr: 'Hunnenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020252',
    nr: '179',
    typ: 'T',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierhilfe',
    datum: '12.07.20',
    adr: 'Boschstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020253',
    nr: '178',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '10/1; Feuerwehr Bobingen 30/1',
    title: 'KTL-Einsatz',
    datum: '12.07.20',
    adr: 'St.-Johannes-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020250',
    nr: '177',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '10/1, 30/1, 40/2',
    title: 'KTL-Einsatz',
    datum: '12.07.20',
    adr: 'Donauwörther Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020249',
    nr: '176',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '10.07.20',
    adr: 'Königsbrunner Straße, Oberottmarshausen',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020248',
    nr: '175',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 40/2, 21/1, 14/1',
    title: 'Brand Freifläche',
    datum: '10.07.20',
    adr: 'Mühlstraße',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020247',
    nr: '174',
    typ: 'S',
    stw: 'HvO (Helfer vor Ort)',
    fzg: '10/1, 40/2, 30/1',
    title: 'KTL-Einsatz',
    datum: '10.07.20',
    adr: 'Eichenplatz',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020246',
    nr: '173',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 65/1',
    title: 'Verkehrsunfall mit 2 PKW',
    datum: '09.07.20',
    adr: 'Lechstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020245',
    nr: '172',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '10/1, 40/2, 30/1',
    title: 'KTL-Einsatz',
    datum: '09.07.20',
    adr: 'Liebenauer Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020337',
    nr: '171',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Fundtier',
    datum: '08.07.20',
    adr: 'Brunnenbachstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020244',
    nr: '170',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 40/2, 21/1, 48/1',
    title: 'Brennender Kiosk',
    datum: '08.07.20',
    adr: 'Sperberstraße',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020336',
    nr: '169',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierrettung',
    datum: '07.07.20',
    adr: 'Röntgenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020242',
    nr: '168',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 14/1, 55/1',
    title: 'VU PKW gegen Traktor',
    datum: '05.07.20',
    adr: 'ST2380',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020241',
    nr: '167',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '05.07.20',
    adr: 'Lechfeldgraben',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020240',
    nr: '166',
    typ: 'T',
    stw: 'Sonstige',
    fzg: '10/1, 40/2, 30/1, 40/1',
    title: 'Person droht zu springen',
    datum: '04.07.20',
    adr: 'R.-Wagner-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020239',
    nr: '165',
    typ: 'T',
    stw: 'Unwetter',
    fzg: '65/1',
    title: 'Keller u Wasser',
    datum: '02.07.20',
    adr: 'Germanenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020335',
    nr: '164',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1,40/1, 40/2, 30/1',
    title: 'BMA: Fehlalarm',
    datum: '02.07.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020238',
    nr: '163',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Angebrannte Speisen',
    datum: '02.07.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020237',
    nr: '162',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Wasser i Gebäud',
    datum: '28.06.20',
    adr: 'Hessingstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020236',
    nr: '161',
    typ: 'T',
    stw: 'P in Fahrzeug',
    fzg: '65/1',
    title: 'Türöffnung Fahrzeug',
    datum: '26.06.20',
    adr: 'Heimgartenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020235',
    nr: '160',
    typ: 'S',
    stw: 'Sonstige',
    fzg: '10/1, 40/2',
    title: 'Unterstützung Rettungsdienst ',
    datum: '26.06.20',
    adr: 'St.-Johannes-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020334',
    nr: '159',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierrettung',
    datum: '25.06.20',
    adr: 'Mitterfeldweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020234',
    nr: '158',
    typ: 'S',
    stw: 'HvO (Helfer vor Ort)',
    fzg: '10/1',
    title: 'HvO',
    datum: '22.06.20',
    adr: 'Königsallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020233',
    nr: '157',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Angebrannte Speisen',
    datum: '22.06.20',
    adr: 'Donauwörther Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020232',
    nr: '156',
    typ: 'T',
    stw: 'Sonstige',
    fzg: '10/1, 40/2',
    title: 'Tragehilfe',
    datum: '20.06.20',
    adr: 'St.-Johannes-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020231',
    nr: '155',
    typ: 'T',
    stw: 'Tragehilfe Rettungsdienst',
    fzg: '10/1, 40/2',
    title: 'Tragehilfe Rettungsdienst',
    datum: '20.06.20',
    adr: 'St.-Johannes-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020230',
    nr: '154',
    typ: 'F',
    stw: 'THL 1',
    fzg: 'Nicht ausgerückt ',
    title: 'Fehlalarm ',
    datum: '19.06.20',
    adr: 'Haunstetter Straße, Bobingen',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020229',
    nr: '153',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Abfallcontainer',
    datum: '18.06.20',
    adr: 'Königsallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020228',
    nr: '152',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '18.06.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020222',
    nr: '151',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1',
    title: 'Fzg öffnen akut',
    datum: '16.06.20',
    adr: 'Wandalenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020221',
    nr: '150',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Wassernotdienst',
    datum: '16.06.20',
    adr: 'Alter Postweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020220',
    nr: '149',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 48/1 + VSA, 55/1, 14/1, 65/1; FF Untermeitingen 11/1, 48/1 + VSA',
    title: 'VU B17',
    datum: '12.06.20',
    adr: 'B17 Landsberg » Augsburg',
    foto: false,
    sammel: false,
    ztg: true,
  },
  {
    ID: '2020219',
    nr: '148',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '10/1, 40/2, 30/1',
    title: 'KTL-Einsatz',
    datum: '09.06.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020227',
    nr: '147',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierhilfe',
    datum: '16.06.20',
    adr: 'Forggenseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020226',
    nr: '146',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '40/2',
    title: 'Brand Mülltonne',
    datum: '16.06.20',
    adr: 'Marktstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020218',
    nr: '145',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/2',
    title: 'Brand Mülltonne',
    datum: '04.06.20',
    adr: 'Schulstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020217',
    nr: '144',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Brand Mülltonne',
    datum: '04.06.20',
    adr: 'Frankenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020216',
    nr: '143',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Rauchentwicklung ',
    datum: '02.06.20',
    adr: 'Westendstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020215',
    nr: '142',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Whg öffnen akut',
    datum: '31.05.20',
    adr: 'Chiemseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020225',
    nr: '141',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Tierhilfe',
    datum: '16.06.20',
    adr: '',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020214',
    nr: '140',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '29.05.20',
    adr: 'Lechstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020213',
    nr: '139',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Abfallcontainer',
    datum: '29.05.20',
    adr: 'Alter Postweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020212',
    nr: '138',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '28.05.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020211',
    nr: '137',
    typ: 'T',
    stw: 'THL 2 ',
    fzg: '10/1, 40/2, 65/1',
    title: 'Person eingeklemmt',
    datum: '26.05.20',
    adr: 'Schwabenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020210',
    nr: '136',
    typ: 'F',
    stw: 'THL 1',
    fzg: '',
    title: 'Bergung Kleintier',
    datum: '25.05.20',
    adr: 'Bgm.-Wohlfarth-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020209',
    nr: '135',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Wohnung öffnen',
    datum: '22.05.20',
    adr: 'Enzianstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020208',
    nr: '134',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Wohnung öffnen',
    datum: '22.05.20',
    adr: 'Schäfflerstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020224',
    nr: '133',
    typ: 'S',
    stw: 'Insekten',
    fzg: '65/1',
    title: 'Bienenvolk einfangen',
    datum: '16.06.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020207',
    nr: '132',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2, 21/1, 48/1, 55/1, 14/1',
    title: 'Brennendes Papierlager',
    datum: '21.05.20',
    adr: 'Guldenstraße',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020206',
    nr: '131',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Gegenstand sichern',
    datum: '17.05.20',
    adr: 'Frankenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020223',
    nr: '130',
    typ: 'F',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Fundtier',
    datum: '16.05.20',
    adr: 'Geigerstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020198',
    nr: '129',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '14.05.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020197',
    nr: '128',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '12.05.20',
    adr: 'Welserstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020196',
    nr: '127',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Heckenbrand',
    datum: '06.05.20',
    adr: 'Heidestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020195',
    nr: '126',
    typ: 'S',
    stw: 'Tierhilfe ',
    fzg: '65/1',
    title: 'Verletzter Vogel',
    datum: '05.05.20',
    adr: 'Germanenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020194',
    nr: '125',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '02.05.20',
    adr: 'Mozartstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020193',
    nr: '124',
    typ: 'T',
    stw: 'Sonstige',
    fzg: '10/1, 40/2, 30/1',
    title: 'KTL-Einsatz',
    datum: '01.05.20',
    adr: 'Tegernseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020192',
    nr: '123',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Gebäude sichern',
    datum: '30.04.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020191',
    nr: '122',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '30.04.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020190',
    nr: '121',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 65/1',
    title: 'VU mit Motorrad',
    datum: '27.04.20',
    adr: 'Dornierstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020189',
    nr: '120',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Brand Gartenhütte',
    datum: '25.04.20',
    adr: 'Weidenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020188',
    nr: '119',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '23.04.20',
    adr: 'Blumenallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020187',
    nr: '118',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1, 55/1',
    title: 'Ölspur',
    datum: '21.04.20',
    adr: 'Lechstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020186',
    nr: '117',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 48/1 + VSA',
    title: 'VU B17',
    datum: '18.04.20',
    adr: 'B17 Landsberg » Augsburg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020185',
    nr: '116',
    typ: 'T',
    stw: 'KTL-Einsatz',
    fzg: '30/1, 40/2',
    title: 'KTL-Einsatz',
    datum: '18.04.20',
    adr: 'Zeppelinstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020184',
    nr: '115',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '17.04.20',
    adr: 'Frankenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020183',
    nr: '114',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '10/1, 40/1, 48/1 + VSA',
    title: 'Irrtum des Meldenden',
    datum: '15.04.20',
    adr: 'B17 Landsberg » Augsburg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020179',
    nr: '113',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '',
    title: 'Eilige Wohnungsöffnung bei Gefahr - Abbestellt',
    datum: '12.04.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020181',
    nr: '112',
    typ: 'S',
    stw: 'Tierrettung',
    fzg: '65/1',
    title: 'Gänse einfangen',
    datum: '12.04.20',
    adr: '',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020182',
    nr: '111',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Auslaufender Kraftstoff',
    datum: '11.04.20',
    adr: 'Birkenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020178',
    nr: '110',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '11.04.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020177',
    nr: '109',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 48/1 + VSA',
    title: 'VU mit einem beteiligten Pkw ',
    datum: '09.04.20',
    adr: 'B17 Augsburg » Landsberg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020176',
    nr: '108',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Kleinbrand',
    datum: '08.04.20',
    adr: 'Haferfeldring',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020175',
    nr: '107',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '08.04.20',
    adr: 'Siedlerweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020174',
    nr: '106',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Brandgeruch',
    datum: '05.04.20',
    adr: 'Richthofenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020173',
    nr: '105',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Keller unter Wasser',
    datum: '04.04.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020205',
    nr: '104',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: '',
    datum: '04.04.20',
    adr: 'Angerstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020172',
    nr: '103',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1',
    title: 'Heckenbrand',
    datum: '04.04.20',
    adr: 'Lavendelring',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020204',
    nr: '102',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '65/1',
    title: 'Verletzter Schwan',
    datum: '20.04.20',
    adr: 'Lechstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020171',
    nr: '101',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '02.04.20',
    adr: 'Pappelstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020170',
    nr: '100',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2; FF Oberottmarshausen, FF Kleinaitingen',
    title: 'Zimmerbrand - Fehlalarm ',
    datum: '29.03.20',
    adr: 'Lechfeld-Nord, Kleinaitingen',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020169',
    nr: '99',
    typ: 'B',
    stw: 'B Wald',
    fzg: '10/1, 21/1; BF Augsburg, FF Haunstetten, Bergheim, Inningen',
    title: 'Waldbrand',
    datum: '27.03.20',
    adr: 'Stadtgebiet Augsburg,',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020168',
    nr: '98',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Bergung Kl Tier',
    datum: '25.03.20',
    adr: 'Bobinger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020167',
    nr: '97',
    typ: 'T',
    stw: 'Tragehilfe Rettungsdienst',
    fzg: '10/1, 40/2',
    title: 'Unterstützung Rettungsdienst',
    datum: '20.03.20',
    adr: 'Pfalzstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020166',
    nr: '96',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 55/1',
    title: 'VU mit zwei beteiligten PKW',
    datum: '20.03.20',
    adr: 'Egerländer Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020165',
    nr: '95',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '17.03.20',
    adr: 'Rosenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020164',
    nr: '94',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 65/1',
    title: 'VU mit zwei beteiligten PKW',
    datum: '17.03.20',
    adr: 'R.-Wagner-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020163',
    nr: '93',
    typ: 'T',
    stw: 'Tragehilfe',
    fzg: '40/2',
    title: 'Tragehilfe Rettungsdienst ',
    datum: '16.03.20',
    adr: 'St.-Johannes-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020162',
    nr: '92',
    typ: 'T',
    stw: 'THL 2',
    fzg: '10/1, 62/1, 55/1, 40/2; FF Oberottmarshausen 21/1, 43/1',
    title: 'Verkehrsunfall',
    datum: '06.03.20',
    adr: 'Alemannenstraße, Oberottmarshausen',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020159',
    nr: '91',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1',
    title: 'BMA: Fehlalarm',
    datum: '05.03.20',
    adr: 'Schwabenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020161',
    nr: '90',
    typ: 'T',
    stw: 'P-Aufzug',
    fzg: '65/1',
    title: 'Person in Aufzug',
    datum: '05.03.20',
    adr: 'Wandalenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020158',
    nr: '89',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 48/1 + VSA; FF Klosterlechfeld',
    title: 'Verkehrslenkung',
    datum: '04.03.20',
    adr: 'B17 Augsburg » Landsberg',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020156',
    nr: '88',
    typ: 'B',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA',
    datum: '03.03.20',
    adr: 'Alter Postweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020155',
    nr: '87',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 65/1',
    title: 'VU mit  zwei PKW',
    datum: '29.02.20',
    adr: 'Fohlenhofstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020203',
    nr: '86',
    typ: 'T',
    stw: 'Unwetternotdienst',
    fzg: '40/2',
    title: 'Umgestürzter Bauzaun',
    datum: '27.02.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020202',
    nr: '85',
    typ: 'T',
    stw: 'Unwetternotdienst',
    fzg: '40/2',
    title: 'Umgestürzter Bauzaun',
    datum: '27.02.20',
    adr: 'Adalbert-Stifter-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020201',
    nr: '84',
    typ: 'T',
    stw: 'Unwetternotdienst',
    fzg: '65/1',
    title: 'Umgestürzter Bauzaun',
    datum: '27.02.20',
    adr: 'Lechstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020200',
    nr: '83',
    typ: 'T',
    stw: 'Unwetternotdienst',
    fzg: '65/1',
    title: 'Sturmschaden',
    datum: '27.02.20',
    adr: 'Hunnenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020154',
    nr: '82',
    typ: 'T',
    stw: 'Unwetter',
    fzg: '10/1, 40/2, 40/1',
    title: 'Bauteil lose',
    datum: '27.02.20',
    adr: 'Angerstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020153',
    nr: '81',
    typ: 'S',
    stw: 'Erkundung',
    fzg: '10/1',
    title: 'Erkundung',
    datum: '27.02.20',
    adr: 'Landsberger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020152',
    nr: '80',
    typ: 'W',
    stw: 'Sicherheitswache',
    fzg: '14/1',
    title: 'SHW Veranstaltung',
    datum: '26.02.20',
    adr: 'Königsallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020122',
    nr: '79',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '26.02.20',
    adr: 'Donauwörther Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020120',
    nr: '78',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Straße reinigen',
    datum: '24.02.20',
    adr: 'Jägerstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020199',
    nr: '77',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Ölspur',
    datum: '24.02.20',
    adr: 'Jägerstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020121',
    nr: '76',
    typ: 'W',
    stw: 'Sicherheitswache',
    fzg: '14/1',
    title: 'Sicherheitswache Kinderfaschingsball',
    datum: '24.02.20',
    adr: 'Karwendelstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020119',
    nr: '75',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '23.02.20',
    adr: 'Wandalenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020118',
    nr: '74',
    typ: 'T',
    stw: 'THL 2',
    fzg: '10/1, 40/2, 40/1, 48/1 + VSA, 14/1, 55/1, 62/1',
    title: 'VU B17',
    datum: '23.02.20',
    adr: 'B17 Landsberg » Augsburg',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020117',
    nr: '73',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Tierhilfe',
    datum: '21.02.20',
    adr: 'Meringer Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020116',
    nr: '72',
    typ: 'T',
    stw: 'THL 1',
    fzg: '10/1, 40/2, 48/1 + VSA',
    title: 'Auslaufende Betriebsstoffe',
    datum: '21.02.20',
    adr: 'B17 Landsberg » Augsburg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020115',
    nr: '71',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '10/1, 40/1, 48/1 + VSA, 21/1',
    title: 'Fehlalarm - keine Feststellung',
    datum: '21.02.20',
    adr: 'B17 Landsberg > Augs 720  1.5',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020114',
    nr: '70',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '21.02.20',
    adr: 'Gotenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020113',
    nr: '69',
    typ: 'S',
    stw: 'HvO',
    fzg: '10/1',
    title: 'Medizinische Hilfeleistung',
    datum: '20.02.20',
    adr: 'Blumenallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020086',
    nr: '68',
    typ: 'T',
    stw: 'P eingeklemmt',
    fzg: '10/1, 40/2, 62/1; FF Bobingen',
    title: 'Person von Zug erfasst',
    datum: '18.02.20',
    adr: 'Bahnstrecke Augsburg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020085',
    nr: '67',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Brandgeruch',
    datum: '18.02.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020084',
    nr: '66',
    typ: 'B',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'Rauchentwicklung aus Keller',
    datum: '17.02.20',
    adr: 'Simpertstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020083',
    nr: '65',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '',
    title: 'Brand Abfallbehälter',
    datum: '15.02.20',
    adr: 'Bei der Krone',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020151',
    nr: '64',
    typ: 'S',
    stw: 'THL 1',
    fzg: '14/1',
    title: 'Tierrettung',
    datum: '15.02.20',
    adr: 'B17 Landsberg » Augsburg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020082',
    nr: '63',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '15.02.20',
    adr: 'Chiemseestraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020081',
    nr: '62',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '14.02.20',
    adr: 'Eschenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020080',
    nr: '61',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Kleinbrand',
    datum: '13.02.20',
    adr: 'Wasserhausweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020079',
    nr: '60',
    typ: 'S',
    stw: 'HvO',
    fzg: '10/1',
    title: 'Medizinische Hilfeleistung',
    datum: '13.02.20',
    adr: 'Geranienweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020150',
    nr: '59',
    typ: 'T',
    stw: 'THL 1',
    fzg: '30/1',
    title: 'Sturmschaden',
    datum: '12.02.20',
    adr: 'Oberottmarshausen',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020078',
    nr: '58',
    typ: 'T',
    stw: 'Unwetternotdienst',
    fzg: '30/1',
    title: 'Lose Verkleidung an Gebäude gesichert',
    datum: '11.02.20',
    adr: 'Donauwörther Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020077',
    nr: '57',
    typ: 'S',
    stw: 'Tierhilfe ',
    fzg: '65/1',
    title: 'Tiertransport',
    datum: '11.02.20',
    adr: 'Bgm.-Wohlfarth-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020076',
    nr: '56',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '10.02.20',
    adr: 'Bgm.-Wohlfarth-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020027',
    nr: '28',
    typ: 'T',
    stw: 'Unwetter',
    fzg: '10/1, 14/1, 65/1, 40/1, 40/2, 30/1,',
    title: 'Unwetter im Stadtgebiet',
    datum: '10.02.20',
    adr: 'Messerschmittring',
    foto: false,
    sammel: '28',
    ztg: false,
  },
  {
    ID: '2020028',
    nr: '27',
    typ: 'W',
    stw: 'Sicherheitswache',
    fzg: '40/2',
    title: 'Sicherheitswache',
    datum: '09.02.20',
    adr: 'Messerschmittring',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020026',
    nr: '26',
    typ: 'T',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 65/1',
    title: 'Verkehrsunfall mit PKW',
    datum: '05.02.20',
    adr: 'Gartenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020025',
    nr: '25',
    typ: 'B',
    stw: 'Brand 3',
    fzg: '10/1, 40/1, 48/1 + VSA, 40/2',
    title: 'LKW-Brand',
    datum: '04.02.20',
    adr: 'B17 Augsburg » Landsberg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020024',
    nr: '24',
    typ: 'T',
    stw: 'Unwetter',
    fzg: '14/1, 55/1',
    title: 'Überschwemmung',
    datum: '02.02.20',
    adr: 'Gartenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020023',
    nr: '23',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '02.02.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020022',
    nr: '22',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Ölspur',
    datum: '01.02.20',
    adr: 'Schwabenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020021',
    nr: '21',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '31.01.20',
    adr: 'A.-Schweitzer-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020020',
    nr: '20',
    typ: 'F',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Brandgeruch - Irrtum des Meldenden ',
    datum: '29.01.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020018',
    nr: '19',
    typ: 'T',
    stw: 'THL 2',
    fzg: '10/1, 62/1, 55/1, 40/2; FF Bobingen',
    title: 'Nachbarschaftshilfe Einsturz Gebäude ',
    datum: '26.01.20',
    adr: 'Lindauer Straße, Bobingen',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020019',
    nr: '18',
    typ: 'S',
    stw: 'Tierhilfe ',
    fzg: '30/1',
    title: 'Katze auf Baum',
    datum: '25.01.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020016',
    nr: '17',
    typ: 'S',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Verletztes Tier',
    datum: '25.01.20',
    adr: 'Bgm.-Wohlfarth-Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020017',
    nr: '16',
    typ: 'S',
    stw: 'Tierhilfe',
    fzg: '30/1',
    title: 'Katze auf Baum',
    datum: '25.01.20',
    adr: 'Enzianstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020015',
    nr: '15',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '24.01.20',
    adr: 'Augsburger Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020014',
    nr: '14',
    typ: 'F',
    stw: 'Brand 3 - BMA',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '23.01.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020013',
    nr: '13',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 48/1 + VSA',
    title: 'VU B17',
    datum: '22.01.20',
    adr: 'B17 Augsburg > Lands 700 0.0',
    foto: true,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020010',
    nr: '12',
    typ: 'T',
    stw: 'THL 2 - VU 1',
    fzg: '10/1, 40/2, 48/1 + VSA',
    title: 'VU B17',
    datum: '21.01.20',
    adr: 'B17 Landsberg » Augsburg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020012',
    nr: '11',
    typ: 'W',
    stw: 'Sicherheitswache ',
    fzg: '14/1',
    title: 'Sicherheitswache Feuershow',
    datum: '18.01.20',
    adr: 'Königsallee',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020011',
    nr: '10',
    typ: 'T',
    stw: 'THL 1',
    fzg: '65/1',
    title: 'Ölspur',
    datum: '18.01.20',
    adr: 'Rathausstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020009',
    nr: '9',
    typ: 'F',
    stw: 'THL ABC',
    fzg: '10/1, 40/2, 40/1',
    title: 'Gas-Geruch',
    datum: '17.01.20',
    adr: 'Augustusstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020007',
    nr: '8',
    typ: 'B',
    stw: 'Brand 1',
    fzg: '10/1, 40/1',
    title: 'Brand Mülleimer ',
    datum: '14.01.20',
    adr: 'Eichenplatz',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020006',
    nr: '7',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '07.01.20',
    adr: 'Falkenweg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020008',
    nr: '6',
    typ: 'W',
    stw: 'Sicherheitswache ',
    fzg: '14/1',
    title: 'Sicherheitswache Dreikönigskonzert',
    datum: '06.01.20',
    adr: 'Karwendelstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020005',
    nr: '5',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '06.01.20',
    adr: 'Asternstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020004',
    nr: '4',
    typ: 'F',
    stw: 'THL 1 - VU 1',
    fzg: '10/1, 40/2, 48/1 + VSA',
    title: 'Irrtum des Meldenden',
    datum: '04.01.20',
    adr: 'B17 Augsburg » Landsberg',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020003',
    nr: '3',
    typ: 'F',
    stw: 'Brand 3 Person',
    fzg: '10/1, 40/1, 30/1, 40/2',
    title: 'BMA: Fehlalarm',
    datum: '02.01.20',
    adr: 'Haunstetter Straße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020002',
    nr: '2',
    typ: 'T',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '01.01.20',
    adr: 'Grüntenstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
  {
    ID: '2020001',
    nr: '1',
    typ: 'F',
    stw: 'P Wohnung',
    fzg: '65/1, 30/1',
    title: 'Eilige Wohnungsöffnung bei Gefahr',
    datum: '01.01.20',
    adr: 'Pfalzstraße',
    foto: false,
    sammel: false,
    ztg: false,
  },
]
